### PR TITLE
Dbm working 7

### PR DESCRIPTION
**Pull request by dbmcclain**
not ready for merge - just make visible to team

### CODE REVIEW

**Comment by dbmcclain** [comment]
Should probably merge this branch now. Crypto lib support has been significantly extended. We have startup init checksum validation on curve constants, and unit test code to check against BLS signature to be sure no attacks have substituted curves on us.

I expect no code breakage for anyone. If it happens, let me know.

**Comment by dbmcclain** [comment]
I give up... this PR runs just fine locally, all unit tests pass, no warnings issued. But GitLab consistently fails to perform. Sheesh! I don't know what else to try...

**Comment by dbmcclain** [comment]
ready to merge

**Comment by rtsisyk** [comment]
Re-based and pushed with minor cleanups.

**Pull request closed without merging**
