### PR TITLE
Provisional implementation of Randhound++ protocol

### PR DESCRIPTION
**Pull request by dbmcclain**
See #33

### CODE REVIEW

**Comment by rtsisyk** [comment]
@dbmcclain please just push to a branch without creating a pull request if you don't need review.

**Comment by echupriyanov** [comment]
> @dbmcclain please just push to a branch without creating a pull request if you don't need review.

@rtsisyk At Emotiq we were sticking to habit create PR earlier to let others monitor work in progress.
And I'd prefer to keep that practice

**Comment by rtsisyk** [comment]
I don't know how to create an empty pull request when I start to work on a new feature, so you will not be able to track the progress.

**Comment by dbmcclain** [comment]
I just push my new branch to create this PR. I haven't asked for any review yet, and I will compress all the commits before doing so...

This PR is just so you can observe progress, if you are interested...

**Pull request merged**
