### PR TITLE
fix Fq51::is_odd() corner cases

### PR DESCRIPTION
**Pull request by dbmcclain**
perform gnorm() ahead of parity testing to remove modular excesses from redundant encodings. The alternate, excess, encodings have opposite parity.

### CODE REVIEW

**Comment by rtsisyk** [comment]
Please rebase.

**Comment by dbmcclain** [comment]
rebased

**Comment by rtsisyk** [comment]
Sorry, I didn't get it at the first look. Could you please elaborate?

**Comment by dbmcclain** [comment]
I spent the weekend making sure that I properly understood gnorm(). 
It needs the sequence gneg(), scr(), gneg(), scr(), scr(). That's all. But very important.

**Comment by dbmcclain** [comment]
I found a lurking assert!() in the conversion from U256 -> Fq, which then converts to Fq51. The function Fq51::try_from_bytes() offers to return an error, but the From<U256> for Fq does not.

These functions are called when decompressing points to Curve1174.  We don't want that assert!() to bite us later, so intentional range checking ahead of Fq::from(U256) was inserted in Fq51::try_from_bytes()

**Comment by dbmcclain** [comment]
rebase on dev

**Comment by dbmcclain** [comment]
Hi Roman, you already approved this several days ago. I merely made a correction that was needed. Can you please approve this so that we can mitigate glaring flaws in our test platforms?

**Pull request merged**
