### PR TITLE
VDF based on Buterin's Sqrt Algorithm

### PR DESCRIPTION
**Pull request by dbmcclain**

### CODE REVIEW

**Comment by dbmcclain** [comment]
Cleanup as instructed - except... 
still needs extern crate declaration in stub code crypto/stubs/vdf_field/src/lib.rs

**Comment by dbmcclain** [comment]
This version of VDF should work for any integer difficulty all the way down to zero.

**Comment by rtsisyk** [comment]
It fails with NotInField on some inputs:

```
--- a/crypto/src/vdf/mod.rs
+++ b/crypto/src/vdf/mod.rs
@@ -197,9 +197,9 @@ fn test_fv() {
     use super::hash::Hash;
     use std::time::SystemTime;
     let vdf = VDF::new();
-    let challenge = Hash::from_str("Testing").bits();
     let mult = 5000;
     for ix in 0..11 {
+        let challenge = Hash::random().to_bytes();
         let difficulty = ix * mult;
         let start = SystemTime::now();
         let ans = vdf.solve(&challenge, difficulty).unwrap();
```

**Comment by dbmcclain** [comment]
found and fixed the errors

**Pull request merged**
