### PR TITLE
Prepare for remote console

### PR DESCRIPTION
**Pull request by rtsisyk**
Please review individual commits.

### CODE REVIEW

**Comment by rtsisyk** [comment]
I haven't touched `net send` and `net publish` in this patch. The new API allow to subscribe to any particular unicast/broadcast topic. It can be used for debugging purposes. For example, someone can subscribe to `consensus` topic and start auditing messages.  I plan add `net subscribe broadcast TOPIC` and `net subscribe unicast TOPIC` to Console after switching to Public API. I don't see any reason to don't allow arbitrary topics in Console. Of course, I can subscribe Console to "console" topic by default.

**Comment by echupriyanov** [comment]
You can't subscribe to arbitrary topics in broadcast communications during runtime. To propagate message through broadcast, all involved nodes should be subscribed to the same topic. It just makes no sense to subscribe to topic on only one or couple of nodes. Intermediate nodes just wouldn't pass such messages.

**Comment by rtsisyk** [comment]
Yes, but you can subscribe to existing topics, e.g. "block" or "consensus" via API.

**Comment by echupriyanov** [comment]
Yes, exactly. That's why I suggest to subscribe WebSocket/Node service to common topic exclusively to be used by console.

**Comment by rtsisyk** [comment]
Agreed to enable `console` topic by default.

**Comment by rtsisyk** [comment]
Replaced by #981

**Pull request closed without merging**
