### PR TITLE
Validate input and output range hashes of block

### PR DESCRIPTION
**Pull request by rtsisyk**
- Use Merkle tree for block.header.outputs_range_hash calculation
- Use chained hash for block.header.inputs_range_hash calculation
- Add checks to block.validate()
- Add tests

Needed for #47

### CODE REVIEW

**Comment by dbmcclain** [comment]
Pedersen commitments balancing is one aspect. Where are amounts actually validated? (Bulletproofs)

**Comment by rtsisyk** [comment]
Bulletproofs are only validated in transactions. Let me add this check too.

**Comment by rtsisyk** [comment]
Sorry, I was wrong. BulletProofs are already validated by Block::validate():
See https://github.com/stegos/stegos/blob/afecb6a59429e5f2a00184ce5b400210ad14f5c5/blockchain/src/block.rs#L300-L302

**Comment by rtsisyk** [comment]
I added comments, rebased and pushed this pull request as d3560780410cfe85943202e66e8d81e0f9f29e38.

**Pull request closed without merging**
